name: Build Android APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Extract Project
        run: |
          unzip Frat.zip -d ./www/
          # التأكد من وجود index.html في المجلد الرئيسي للـ www
          SUB_DIR=$(find ./www -name "index.html" -exec dirname {} \;)
          cp -r $SUB_DIR/. ./www/ || true

      - name: Build Android APK
        uses: ionichealth/cordova-build-action@v1
        with:
          platform: android
          args: --debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Prayer-App-Final-Success
          path: platforms/android/app/build/outputs/apk/debug/app-debug.apk
